"""add complaints table

Revision ID: de57517ded4b
Revises: f8a2c9d41e03
Create Date: 2026-07-26 06:46:47.649742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'de57517ded4b'
down_revision: Union[str, None] = 'f8a2c9d41e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consumidor_nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consumidor_domicilio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consumidor_documento_tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consumidor_documento_numero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consumidor_telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consumidor_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('es_menor_edad', sa.Boolean(), nullable=False),
    sa.Column('apoderado_nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bien_tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bien_descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monto_reclamado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('detalle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pedido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_number'), 'complaints', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_number'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
